// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD76ZvmL-oiyAL9DiAfQgcH6TlpcHI_EiA',
    appId: '1:582638918651:web:6eb050cef9ad2f45f5c95e',
    messagingSenderId: '582638918651',
    projectId: 'myflutterrr',
    authDomain: 'myflutterrr.firebaseapp.com',
    storageBucket: 'myflutterrr.firebasestorage.app',
    measurementId: 'G-331VG916BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6BHj8Wz48IcE8FVrFrr7HHTu65yNP7CM',
    appId: '1:582638918651:android:d1f1017b25deb489f5c95e',
    messagingSenderId: '582638918651',
    projectId: 'myflutterrr',
    storageBucket: 'myflutterrr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXyMH0GQCKv1zUQlHTJGoSA-raDwqmdg',
    appId: '1:582638918651:ios:dab4b452b4aaaafaf5c95e',
    messagingSenderId: '582638918651',
    projectId: 'myflutterrr',
    storageBucket: 'myflutterrr.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbXyMH0GQCKv1zUQlHTJGoSA-raDwqmdg',
    appId: '1:582638918651:ios:dab4b452b4aaaafaf5c95e',
    messagingSenderId: '582638918651',
    projectId: 'myflutterrr',
    storageBucket: 'myflutterrr.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD76ZvmL-oiyAL9DiAfQgcH6TlpcHI_EiA',
    appId: '1:582638918651:web:a0a716b7b555408cf5c95e',
    messagingSenderId: '582638918651',
    projectId: 'myflutterrr',
    authDomain: 'myflutterrr.firebaseapp.com',
    storageBucket: 'myflutterrr.firebasestorage.app',
    measurementId: 'G-RLFZ1150EY',
  );
}
